# Generated by Django 5.0 on 2023-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='examen',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
