# Generated by Django 5.0 on 2023-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_examen_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='entregado',
        ),
        migrations.AddField(
            model_name='examen',
            name='nota',
            field=models.IntegerField(default=None),
        ),
    ]
