# Generated by Django 5.0 on 2024-01-21 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutoEducativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nota',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='legajo',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
