# Generated by Django 5.0 on 2024-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutoEducativo', '0002_alter_curso_comision_alter_estudiante_legajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='legajo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
