# Generated by Django 5.0 on 2024-01-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutoEducativo', '0003_alter_curso_comision_alter_estudiante_legajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='InstitutoEducativo.estudiante'),
        ),
    ]
